### ISSUE TITLE
discord.py update

### ISSUE THREAD

**Issue by VisoXC** [ICEGXG/UntitledNuker#5]
it sadly doesnt work anymore after discord.py had an update

```
An error occured while logging:
Traceback (most recent call last):
  File "UntitledNuker.py", line 607, in <module>
    for i in range(amount):
        ^^^^^^^^^^^^^^^^^^^^
  File "discord\client.py", line 828, in run
  File "asyncio\runners.py", line 190, in run
  File "asyncio\runners.py", line 118, in run
  File "asyncio\base_events.py", line 653, in run_until_complete
  File "discord\client.py", line 817, in runner
  File "discord\client.py", line 746, in start
  File "discord\client.py", line 627, in connect
  File "discord\gateway.py", line 623, in poll_event
  File "discord\gateway.py", line 573, in received_message
  File "discord\state.py", line 1209, in parse_guild_create
  File "discord\state.py", line 1147, in _get_create_guild
  File "discord\guild.py", line 491, in _from_data
  File "discord\guild.py", line 492, in <lambda>
  File "discord\state.py", line 379, in store_sticker
  File "discord\sticker.py", line 273, in __init__
  File "discord\sticker.py", line 416, in _from_data
  File "discord\sticker.py", line 280, in _from_data
  File "discord\enums.py", line 539, in file_extension
KeyError: <StickerFormatType.unknown_4: 4>
```

**Comment by ICEGXG** [comment]
Strange, it worked fine (at least started) on discord.py v2.3.2
What exactly were you doing when you got this error?
